sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WRIJcQqYVDgQNuRyCodii1dMAnftfopTJCU6T/8qoaQSHRSj70lVHvPBim3mHY/wxYoDhOiuhCH51Q3ipbefl6hOiGSmIJGRo1qbxIMWUOa3CjjaUBJbSuf3g6aSBVqKAqVAnTipeInz3nGdoK8qJ3fc8YM+8Cu/SnQgcm7haS1SdBVZRNVGzBaJTP0tKAsLA2PHKyBoDzVu8463VE/DB3DxWwaChtYg0zehOQ02ZnPnnOw0uUh7Eb8CdNy3E4l4CvuR55QISWbKOSUPdt5Oq1Y4w52M6VFzk0Lzcar+gmUwfVB/ohkV+w2nS//0TyTEviIkiFjaK/Bf9bagqsNnxcAuCgF9Kc5Vbg/rVz6letfi+oPnOgShruWTaB7PhqwwKYucQGD8CrbyCiqaaPGrtCLmxcc932MQ/xnZIJggAsCW32y1kYehUKfi6Mzgv/51FFqTpPFxvlXceISCQzbAMzPF/ac5iwOCaK5a3og7K6ZI1JI7ylc0mZ4MmixOjwwhzz4f3QJ+28tX09hICghCKNeoMTK8g1O8ZGgN1TeDYfLtuto7G6C+OTqpJgWRr+3gj5qWYPmZVze2laa54PnNbWgQUUX2OeI3M6zGNW4ieBKVwPHDjNE9wG0xdCXwgk9m1FdlBulfFdUQ24YyNFmMsp0dRiRXq1zt1hcDym6EeVA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Phil-the-Fiddler_671
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy